// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Represents a streamed chunk of a chat completion response returned by model, based on the provided input.
public type createChatCompletionStreamResponse record {
    # A unique identifier for the chat completion. Each chunk has the same ID.
    string id;
    # A list of chat completion choices. Can contain more than one elements if `n` is greater than 1.
    createChatCompletionStreamResponse_choices[] choices;
    # The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
    int created;
    # The model to generate the completion.
    string model;
    # This fingerprint represents the backend configuration that the model runs with.
    # Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
    string system_fingerprint?;
    # The object type, which is always `chat.completion.chunk`.
    "chat.completion.chunk" 'object;
};

# Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
public type chatCompletionFunctionCall record {
    # The name of the function to call.
    string name;
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments;
};

# Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
public type chatCompletionFunctionCallOption record {
    # The name of the function to call.
    string name;
};

public type chatCompletionRequestDeveloperMessageContentPart chatCompletionRequestMessageContentPartText;

# Options for streaming response. Only set this when you set `stream: true`.
public type chatCompletionStreamOptions record {
    # If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array. All other chunks will also include a `usage` field, but with a null value.
    boolean include_usage?;
};

# Static predicted output content, such as the content of a text file that is being regenerated.
public type PredictionContent record {
    # The type of the predicted content you want to provide. This type is currently always `content`.
    "content" 'type;
    # The content that should be matched when generating a model response. If generated tokens would match this content, the entire model response can be returned much more quickly.
    string|chatCompletionRequestMessageContentPartText[] content;
};

public type chatCompletionMessageToolCallChunk_function record {
    # The name of the function to call.
    string name?;
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments?;
};

public type chatCompletionMessageToolCall record {
    # The ID of the tool call.
    string id;
    # The type of the tool call, in this case `function`.
    toolCallType 'type;
    # The function that the model called.
    chatCompletionMessageToolCall_function 'function;
};

public type contentFilterIdResult record {
    *contentFilterResultBase;
    string id;
};

# If the audio output modality is requested, this object contains data
# about the audio response from the model. [Learn more](/docs/guides/audio).
public type chatCompletionResponseMessage_audio record {
    # Unique identifier for this audio response.
    string id;
    # The Unix timestamp (in seconds) for when this audio response will
    # no longer be accessible on the server for use in multi-turn
    # conversations.
    int expires_at;
    # Base64 encoded audio bytes generated by the model, in the format
    # specified in the request.
    string data;
    # Transcript of the audio generated by the model.
    string transcript;
};

public type chatCompletionRequestToolMessageContentPart chatCompletionRequestMessageContentPartText;

public type contentFilterDetectedResult record {
    *contentFilterResultBase;
    boolean detected;
};

@deprecated
public type chatCompletionRequestFunctionMessage record {
    # The role of the messages author, in this case `function`.
    "function" role;
    # The contents of the function message.
    string? content;
    # The name of the function to call.
    string name;
};

# A chat completion delta generated by streamed model responses.
public type chatCompletionStreamResponseDelta record {
    # The contents of the chunk message.
    string? content?;
    # Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    chatCompletionStreamResponseDelta_function_call function_call?;
    chatCompletionMessageToolCallChunk[] tool_calls?;
    # The role of the author of this message.
    "system"|"user"|"assistant"|"tool" role?;
    # The refusal message generated by the model.
    string? refusal?;
};

public type contentFilterDetectedWithCompletionTextSpansResult record {
    *contentFilterDetectedResult;
    boolean filtered;
    contentFilterCompletionTextSpan[] details;
};

public type chatCompletionsRequestCommon record {
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    # We generally recommend altering this or `top_p` but not both.
    decimal? temperature = 1;
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    # We generally recommend altering this or `temperature` but not both.
    decimal? top_p = 1;
    # If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a `data: [DONE]` message.
    boolean? 'stream = false;
    # Up to 4 sequences where the API will stop generating further tokens.
    string|string[]? stop?;
    # The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return will be (4096 - prompt tokens). This is not compatible with o1 series models.
    int? max_tokens = 4096;
    # An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and reasoning tokens. This is only supported in o1 series models. Will expand the support to other models in future API release.
    int? max_completion_tokens?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    decimal? presence_penalty = 0;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    decimal? frequency_penalty = 0;
    # Modify the likelihood of specified tokens appearing in the completion. Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
    record {}? logit_bias?;
    # Whether or not to store the output of this chat completion request for use in our model distillation or evaluation products.
    boolean? store?;
    # Developer-defined tags and values used for filtering completions in the stored completions dashboard.
    record {|string...;|}? metadata?;
    # A unique identifier representing your end-user, which can help Azure OpenAI to monitor and detect abuse.
    string user?;
};

# Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
# 
# # Deprecated
@deprecated
public type chatCompletionRequestAssistantMessage_function_call record {
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments;
    # The name of the function to call.
    string name;
};

public type chatCompletionRequestSystemMessageContentPart chatCompletionRequestMessageContentPartText;

# The function that the model called.
public type chatCompletionMessageToolCall_function record {
    # The name of the function to call.
    string name;
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Provides Auth configurations needed when communicating with a remote HTTP endpoint.
    http:BearerTokenConfig|ApiKeysConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# The type of the tool call, in this case `function`.
public type toolCallType "function";

# The schema for the response format, described as a JSON Schema object.
public type ResponseFormatJsonSchemaSchema record {
};

public type contentFilterDetectedWithCitationResult_citation record {
    string URL?;
    string license?;
};

public type chatCompletionRequestMessageContentPartAudio_input_audio record {
    # Base64 encoded audio data.
    string data;
    # The format of the encoded audio data. Currently supports "wav" and "mp3".
    "wav"|"mp3" format;
};

# The tool calls generated by the model, such as function calls.
public type chatCompletionMessageToolCalls chatCompletionMessageToolCall[];

# Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
# 
# # Deprecated
@deprecated
public type chatCompletionStreamResponseDelta_function_call record {
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments?;
    # The name of the function to call.
    string name?;
};

public type chatCompletionRequestMessageContentPartRefusal record {
    # The type of the content part.
    "refusal" 'type;
    # The refusal message generated by the model.
    string refusal;
};

# Whether to enable parallel function calling during tool use.
public type ParallelToolCalls boolean;

# Information about the content filtering category (hate, sexual, violence, self_harm), if it has been detected, as well as the severity level (very_low, low, medium, high-scale that determines the intensity and risk level of harmful content) and if it has been filtered or not. Information about jailbreak content and profanity, if it has been detected, and if it has been filtered or not. And information about customer block list, if it has been filtered and its id.
public type contentFilterPromptResults record {
    *contentFilterResultsBase;
    contentFilterDetectedResult jailbreak?;
    contentFilterDetectedResult indirect_attack?;
};

# Represents the Queries record for the operation: ChatCompletions_Create
public type ChatCompletionsCreateQueries record {
    # api version
    string api\-version;
};

# Learn about [audio inputs](/docs/guides/audio).
public type chatCompletionRequestMessageContentPartAudio record {
    # The type of the content part. Always `input_audio`.
    "input_audio" 'type;
    chatCompletionRequestMessageContentPartAudio_input_audio input_audio;
};

public type chatCompletionTool record {
    # The type of the tool. Currently, only `function` is supported.
    "function" 'type;
    FunctionObject 'function;
};

public type ResponseFormatJsonSchema_json_schema record {
    # A description of what the response format is for, used by the model to determine how to respond in the format.
    string description?;
    # The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    string name;
    # The schema for the response format, described as a JSON Schema object.
    ResponseFormatJsonSchemaSchema schema;
    # Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`.
    boolean? strict = false;
};

public type contentFilterResultBase record {
    boolean filtered;
};

# Parameters for audio output. Required when audio output is requested with
# `modalities: ["audio"]`. [Learn more](/docs/guides/audio).
public type createChatCompletionRequest_audio record {
    # Specifies the voice type. Supported voices are `alloy`, `echo`, 
    # `fable`, `onyx`, `nova`, and `shimmer`.
    "alloy"|"echo"|"fable"|"onyx"|"nova"|"shimmer" voice;
    # Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
    # `opus`, or `pcm16`. 
    "wav"|"mp3"|"flac"|"opus"|"pcm16" format;
};

public type chatCompletionNamedToolChoice_function record {
    # The name of the function to call.
    string name;
};

public type contentFilterDetectedWithCitationResult record {
    *contentFilterDetectedResult;
    boolean filtered;
    contentFilterDetectedWithCitationResult_citation citation?;
};

# User security context contains several parameters that describe the AI application itself, and the end user that interacts with the AI application. These fields assist your security operations teams to investigate and mitigate security incidents by providing a comprehensive approach to protecting your AI applications. [Learn more](https://aka.ms/TP4AI/Documentation/EndUserContext) about protecting AI applications using Microsoft Defender for Cloud.
public type userSecurityContext record {
    # The name of the application. Sensitive personal information should not be included in this field.
    string application_name?;
    # This identifier is the Microsoft Entra ID (formerly Azure Active Directory) user object ID used to authenticate end-users within the generative AI application. Sensitive personal information should not be included in this field.
    string end_user_id?;
    # The Microsoft 365 tenant ID the end user belongs to. It's required when the generative AI application is multi tenant.
    string end_user_tenant_id?;
    # Captures the original client's IP address, accepting both IPv4 and IPv6 formats.
    string source_ip?;
};

# The parameters the functions accepts, described as a JSON Schema object. See the guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. 
# 
# Omitting `parameters` defines a function with an empty parameter list.
public type FunctionParameters record {
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    string api\-key;
|};

public type createChatCompletionStreamResponse_choices record {
    # A chat completion delta generated by streamed model responses.
    chatCompletionStreamResponseDelta delta;
    # Log probability information for the choice.
    createChatCompletionResponse_logprobs? logprobs?;
    # The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
    # `length` if the maximum number of tokens specified in the request was reached,
    # `content_filter` if content was omitted due to a flag from our content filters,
    # `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
    "stop"|"length"|"tool_calls"|"content_filter"|"function_call"? finish_reason;
    # The index of the choice in the list of choices.
    int index;
};

# Content filtering results for a single prompt in the request.
public type promptFilterResult record {
    int prompt_index?;
    # Information about the content filtering category (hate, sexual, violence, self_harm), if it has been detected, as well as the severity level (very_low, low, medium, high-scale that determines the intensity and risk level of harmful content) and if it has been filtered or not. Information about jailbreak content and profanity, if it has been detected, and if it has been filtered or not. And information about customer block list, if it has been filtered and its id.
    contentFilterPromptResults content_filter_results?;
};

# Content filtering results for zero or more prompts in the request. In a streaming request, results for different prompts may arrive at different times or in different orders.
public type promptFilterResults promptFilterResult[];

# Output types that you would like the model to generate for this request.
# Most models are capable of generating text, which is the default:
# 
# `["text"]`
# 
# The `gpt-4o-audio-preview` model can also be used to [generate audio](/docs/guides/audio). To
# request that this model generate both text and audio responses, you can
# use:
# 
# `["text", "audio"]`
public type ChatCompletionModalities ("text"|"audio")[];

# The filtering reason of the retrieved document.
public type filterReason "score"|"rerank";

public type FunctionObject record {
    # A description of what the function does, used by the model to choose when and how to call the function.
    string description?;
    # The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    string name;
    # The parameters the functions accepts, described as a JSON Schema object. See the guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. 
    # 
    # Omitting `parameters` defines a function with an empty parameter list.
    FunctionParameters parameters?;
    # Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](docs/guides/function-calling).
    boolean? strict = false;
};

public type chatCompletionRequestUserMessage record {
    # The contents of the user message.
    string|chatCompletionRequestUserMessageContentPart[] content;
    # The role of the messages author, in this case `user`.
    "user" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

public type chatCompletionRequestMessage ChatCompletionRequestDeveloperMessage|chatCompletionRequestSystemMessage|chatCompletionRequestUserMessage|chatCompletionRequestAssistantMessage|chatCompletionRequestToolMessage|chatCompletionRequestFunctionMessage;

public type chatCompletionRequestMessageContentPartImage record {
    # The type of the content part.
    "image_url" 'type;
    chatCompletionRequestMessageContentPartImage_image_url image_url;
};

# Information about the content filtering results.
public type contentFilterResultsBase record {
    contentFilterSeverityResult sexual?;
    contentFilterSeverityResult violence?;
    contentFilterSeverityResult hate?;
    contentFilterSeverityResult self_harm?;
    contentFilterDetectedResult profanity?;
    # Content filtering results with a detail of content filter ids for the filtered segments.
    contentFilterDetailedResults custom_blocklists?;
    errorBase 'error?;
};

#   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat
#   completions request that should use Azure OpenAI chat extensions to augment the response behavior.
#   The use of this configuration is compatible only with Azure OpenAI.
public type azureChatExtensionType "azure_search"|"azure_cosmos_db"|"elasticsearch"|"mongo_db"|"pinecone";

# Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool. `none` is the default when no tools are present. `auto` is the default if tools are present.
public type chatCompletionToolChoiceOption "none"|"auto"|"required"|chatCompletionNamedToolChoice;

public type ResponseFormatJsonSchema record {
    # The type of response format being defined: `json_schema`
    "json_schema" 'type;
    ResponseFormatJsonSchema_json_schema json_schema;
};

public type createChatCompletionRequest record {
    *chatCompletionsRequestCommon;
    # A list of messages comprising the conversation so far. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb).
    chatCompletionRequestMessage[] messages;
    #   The configuration entries for Azure OpenAI chat extensions that use them.
    #   This additional specification is only compatible with Azure OpenAI.
    azureChatExtensionConfiguration[] data_sources?;
    # **o1 models only** 
    # 
    #  Constrains effort on reasoning for 
    # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    # 
    # Currently supported values are `low`, `medium`, and `high`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.
    "low"|"medium"|"high" reasoning_effort?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
    decimal? frequency_penalty = 0;
    # Modify the likelihood of specified tokens appearing in the completion.
    # 
    # Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
    record {|int...;|}? logit_bias?;
    # Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.
    boolean? logprobs = false;
    # An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.
    int? top_logprobs?;
    # The maximum number of [tokens](/tokenizer) that can be generated in the chat completion.
    # 
    # The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens.
    int? max_tokens?;
    # How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.
    int? n = 1;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
    decimal? presence_penalty = 0;
    # Output types that you would like the model to generate for this request.
    # Most models are capable of generating text, which is the default:
    # 
    # `["text"]`
    # 
    # The `gpt-4o-audio-preview` model can also be used to [generate audio](/docs/guides/audio). To
    # request that this model generate both text and audio responses, you can
    # use:
    # 
    # `["text", "audio"]`
    ChatCompletionModalities modalities?;
    # Configuration for a [Predicted Output](/docs/guides/predicted-outputs), which can greatly improve response times when large parts of the model response are known ahead of time. This is most common when you are regenerating a file with only minor changes to most of the content.
    PredictionContent? prediction?;
    # Parameters for audio output. Required when audio output is requested with
    # `modalities: ["audio"]`. [Learn more](/docs/guides/audio).
    createChatCompletionRequest_audio audio?;
    # Whether to enable parallel function calling during tool use.
    ParallelToolCalls parallel_tool_calls?;
    # An object specifying the format that the model must output. Compatible with [GPT-4o](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-models), [GPT-4o mini](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-models), [GPT-4 Turbo](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-models) and all [GPT-3.5](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-35) Turbo models newer than `gpt-3.5-turbo-1106`.
    # 
    # Setting to `{ "type": "json_schema", "json_schema": {...} }` enables Structured Outputs which guarantees the model will match your supplied JSON schema.
    # 
    # Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.
    # 
    # **Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request. Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.
    ResponseFormatText|ResponseFormatJsonObject|ResponseFormatJsonSchema response_format?;
    # This feature is in Beta.
    # If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.
    # Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
    int? seed?;
    # Up to 4 sequences where the API will stop generating further tokens.
    string|string[]? stop?;
    # If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions).
    boolean? 'stream = false;
    # Options for streaming response. Only set this when you set `stream: true`.
    chatCompletionStreamOptions? stream_options?;
    # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
    # 
    # We generally recommend altering this or `top_p` but not both.
    decimal? temperature = 1;
    # An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
    # 
    # We generally recommend altering this or `temperature` but not both.
    decimal? top_p = 1;
    # A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.
    chatCompletionTool[] tools?;
    # Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool. `none` is the default when no tools are present. `auto` is the default if tools are present.
    chatCompletionToolChoiceOption tool_choice?;
    # Deprecated in favor of `tool_choice`.
    # 
    # Controls which (if any) function is called by the model.
    # `none` means the model will not call a function and instead generates a message.
    # `auto` means the model can pick between generating a message or calling a function.
    # Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
    # 
    # `none` is the default when no functions are present. `auto` is the default if functions are present.
    # 
    # # Deprecated
    @deprecated
    "none"|"auto"|chatCompletionFunctionCallOption function_call?;
    # Deprecated in favor of `tools`.
    # 
    # A list of functions the model may generate JSON inputs for.
    # 
    # # Deprecated
    @deprecated
    chatCompletionFunctions[] functions?;
    # A unique identifier representing your end-user, which can help to monitor and detect abuse.
    string user?;
    # User security context contains several parameters that describe the AI application itself, and the end user that interacts with the AI application. These fields assist your security operations teams to investigate and mitigate security incidents by providing a comprehensive approach to protecting your AI applications. [Learn more](https://aka.ms/TP4AI/Documentation/EndUserContext) about protecting AI applications using Microsoft Defender for Cloud.
    userSecurityContext user_security_context?;
};

public type createChatCompletionResponse_choices record {
    # The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
    # `length` if the maximum number of tokens specified in the request was reached,
    # `content_filter` if content was omitted due to a flag from our content filters,
    # `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
    "stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason;
    # The index of the choice in the list of choices.
    int index;
    # A chat completion message generated by the model.
    chatCompletionResponseMessage message;
    # Information about the content filtering category (hate, sexual, violence, self_harm), if it has been detected, as well as the severity level (very_low, low, medium, high-scale that determines the intensity and risk level of harmful content) and if it has been filtered or not. Information about third party text and profanity, if it has been detected, and if it has been filtered or not. And information about customer block list, if it has been filtered and its id.
    contentFilterChoiceResults content_filter_results?;
    # Log probability information for the choice.
    createChatCompletionResponse_logprobs? logprobs;
};

public type chatCompletionRequestAssistantMessageContentPart chatCompletionRequestMessageContentPartText|chatCompletionRequestMessageContentPartRefusal;

public type chatCompletionRequestSystemMessage record {
    # The contents of the system message.
    string|chatCompletionRequestSystemMessageContentPart[] content;
    # The role of the messages author, in this case `system`.
    "system" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

public type inline_response_200 createChatCompletionResponse|createChatCompletionStreamResponse;

#   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat
#   completions request that should use Azure OpenAI chat extensions to augment the response behavior.
#   The use of this configuration is compatible only with Azure OpenAI.
public type azureChatExtensionConfiguration record {
    #   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat
    #   completions request that should use Azure OpenAI chat extensions to augment the response behavior.
    #   The use of this configuration is compatible only with Azure OpenAI.
    azureChatExtensionType 'type;
};

# Content filtering results with a detail of content filter ids for the filtered segments.
public type contentFilterDetailedResults record {
    *contentFilterResultBase;
    contentFilterIdResult[] details;
};

public type chatCompletionMessageToolCallChunk record {
    int index;
    # The ID of the tool call.
    string id?;
    # The type of the tool. Currently, only `function` is supported.
    "function" 'type?;
    chatCompletionMessageToolCallChunk_function 'function?;
};

# Usage statistics for the completion request.
public type completionUsage record {
    # Number of tokens in the prompt.
    int prompt_tokens;
    # Number of tokens in the generated completion.
    int completion_tokens;
    # Total number of tokens used in the request (prompt + completion).
    int total_tokens;
    # Details of the prompt tokens.
    completionUsage_prompt_tokens_details prompt_tokens_details?;
    # Breakdown of tokens used in a completion.
    completionUsage_completion_tokens_details completion_tokens_details?;
};

# Information about the content filtering category (hate, sexual, violence, self_harm), if it has been detected, as well as the severity level (very_low, low, medium, high-scale that determines the intensity and risk level of harmful content) and if it has been filtered or not. Information about third party text and profanity, if it has been detected, and if it has been filtered or not. And information about customer block list, if it has been filtered and its id.
public type contentFilterChoiceResults record {
    *contentFilterResultsBase;
    contentFilterDetectedResult protected_material_text?;
    contentFilterDetectedWithCitationResult protected_material_code?;
    contentFilterDetectedWithCompletionTextSpansResult ungrounded_material?;
};

public type chatCompletionRequestUserMessageContentPart chatCompletionRequestMessageContentPartText|chatCompletionRequestMessageContentPartImage|chatCompletionRequestMessageContentPartAudio;

# The role of the author of the response message.
public type chatCompletionResponseMessageRole "assistant";

public type ResponseFormatText record {
    # The type of response format being defined: `text`
    "text" 'type;
};

public type errorBase record {
    string code?;
    string message?;
};

# citation information for a chat completions response message.
public type citation record {
    # The content of the citation.
    string content;
    # The title of the citation.
    string title?;
    # The URL of the citation.
    string url?;
    # The file path of the citation.
    string filepath?;
    # The chunk ID of the citation.
    string chunk_id?;
    # The rerank score of the retrieved document.
    decimal rerank_score?;
};

# Developer-provided instructions that the model should follow, regardless of messages sent by the user.
# With o1 models and newer, `developer` messages replace the previous `system` messages.
public type ChatCompletionRequestDeveloperMessage record {
    # The contents of the developer message.
    string|chatCompletionRequestDeveloperMessageContentPart[] content;
    # The role of the messages author, in this case `developer`.
    "developer" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

# Specifies a tool the model should use. Use to force the model to call a specific function.
public type chatCompletionNamedToolChoice record {
    # The type of the tool. Currently, only `function` is supported.
    "function" 'type;
    chatCompletionNamedToolChoice_function 'function;
};

# The retrieved document.
public type retrievedDocument record {
    *citation;
    # The search queries used to retrieve the document.
    string[] search_queries;
    # The index of the data source.
    int:Signed32 data_source_index;
    # The original search score of the retrieved document.
    decimal original_search_score;
    # The filtering reason of the retrieved document.
    filterReason filter_reason?;
};

# Describes a span within generated completion text.  Offset 0 is the first UTF32 code point of the completion text.
public type contentFilterCompletionTextSpan record {
    # Offset of the UTF32 code point which begins the span.
    int completion_start_offset;
    # Offset of the first UTF32 code point which is excluded from the span. This field is always equal to completion_start_offset for empty spans. This field is always larger than completion_start_offset for non-empty spans.
    int completion_end_offset;
};

#   A representation of the additional context information available when Azure OpenAI chat extensions are involved
#   in the generation of a corresponding chat completions response. This context information is only populated when
#   using an Azure OpenAI request configured to use a matching extension.
public type azureChatExtensionsMessageContext record {
    # The data source retrieval result, used to generate the assistant message in the response.
    citation[] citations?;
    # The detected intent from the chat history, used to pass to the next turn to carry over the context.
    string intent?;
    # All the retrieved documents.
    retrievedDocument[] all_retrieved_documents?;
};

# Represents a chat completion response returned by model, based on the provided input.
public type createChatCompletionResponse record {
    # A unique identifier for the chat completion.
    string id;
    # Content filtering results for zero or more prompts in the request. In a streaming request, results for different prompts may arrive at different times or in different orders.
    promptFilterResults prompt_filter_results?;
    # A list of chat completion choices. Can be more than one if `n` is greater than 1.
    createChatCompletionResponse_choices[] choices;
    # The Unix timestamp (in seconds) of when the chat completion was created.
    int created;
    # The model used for the chat completion.
    string model;
    # This fingerprint represents the backend configuration that the model runs with.
    # 
    # Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
    string system_fingerprint?;
    # The object type, which is always `chat.completion`.
    "chat.completion" 'object;
    # Usage statistics for the completion request.
    completionUsage usage?;
};

# A chat completion message generated by the model.
public type chatCompletionResponseMessage record {
    # The role of the author of the response message.
    chatCompletionResponseMessageRole role;
    # The refusal message generated by the model.
    string? refusal;
    # The contents of the message.
    string? content;
    # The tool calls generated by the model, such as function calls.
    chatCompletionMessageToolCall[] tool_calls?;
    # Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    chatCompletionFunctionCall function_call?;
    # If the audio output modality is requested, this object contains data
    # about the audio response from the model. [Learn more](/docs/guides/audio).
    chatCompletionResponseMessage_audio audio?;
    #   A representation of the additional context information available when Azure OpenAI chat extensions are involved
    #   in the generation of a corresponding chat completions response. This context information is only populated when
    #   using an Azure OpenAI request configured to use a matching extension.
    azureChatExtensionsMessageContext context?;
};

public type ResponseFormatJsonObject record {
    # The type of response format being defined: `json_object`
    "json_object" 'type;
};

public type chatCompletionTokenLogprob_top_logprobs record {
    # The token.
    string token;
    # The log probability of this token.
    decimal logprob;
    # A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
    int[]? bytes;
};

# Log probability information for the choice.
public type createChatCompletionResponse_logprobs record {
    # A list of message content tokens with log probability information.
    chatCompletionTokenLogprob[]? content;
    # A list of message refusal tokens with log probability information.
    chatCompletionTokenLogprob[]? refusal;
};

public type chatCompletionRequestMessageContentPartText record {
    # The type of the content part.
    "text" 'type;
    # The text content.
    string text;
};

public type chatCompletionRequestAssistantMessage record {
    # The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
    string|chatCompletionRequestAssistantMessageContentPart[]? content?;
    # The refusal message by the assistant.
    string? refusal?;
    # The role of the messages author, in this case `assistant`.
    "assistant" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
    # The tool calls generated by the model, such as function calls.
    chatCompletionMessageToolCalls tool_calls?;
    # Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    chatCompletionRequestAssistantMessage_function_call? function_call?;
};

public type chatCompletionRequestToolMessage record {
    # The role of the messages author, in this case `tool`.
    "tool" role;
    # The contents of the tool message.
    string|chatCompletionRequestToolMessageContentPart[] content;
    # Tool call that this message is responding to.
    string tool_call_id;
};

# Details of the prompt tokens.
public type completionUsage_prompt_tokens_details record {
    # Audio input tokens present in the prompt.
    int audio_tokens?;
    # The number of cached prompt tokens.
    int cached_tokens?;
};

@deprecated
public type chatCompletionFunctions record {
    # A description of what the function does, used by the model to choose when and how to call the function.
    string description?;
    # The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    string name;
    # The parameters the functions accepts, described as a JSON Schema object. See the guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format. 
    # 
    # Omitting `parameters` defines a function with an empty parameter list.
    FunctionParameters parameters?;
};

public type contentFilterSeverityResult record {
    *contentFilterResultBase;
    "safe"|"low"|"medium"|"high" severity;
};

# Breakdown of tokens used in a completion.
public type completionUsage_completion_tokens_details record {
    # When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion.
    int accepted_prediction_tokens?;
    # Audio input tokens generated by the model.
    int audio_tokens?;
    # Tokens generated by the model for reasoning.
    int reasoning_tokens?;
    # When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total  completion tokens for purposes of billing, output, and context window limits.
    int rejected_prediction_tokens?;
};

public type chatCompletionRequestMessageContentPartImage_image_url record {
    # Either a URL of the image or the base64 encoded image data.
    string url;
    # Specifies the detail level of the image. Learn more in the [Vision guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/gpt-with-vision?tabs=rest%2Csystem-assigned%2Cresource#detail-parameter-settings-in-image-processing-low-high-auto).
    "auto"|"low"|"high" detail = "auto";
};

public type chatCompletionTokenLogprob record {
    # The token.
    string token;
    # The log probability of this token.
    decimal logprob;
    # A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
    int[]? bytes;
    # List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.
    chatCompletionTokenLogprob_top_logprobs[] top_logprobs;
};
